### ISSUE TITLE
[SYSTEMML-973] Refactor community members page based on new about layout

### ISSUE THREAD

**Issue by dlesaca** [dlesaca/incubator-systemml-website#1]
https://issues.apache.org/jira/browse/SYSTEMML-973

**Comment by dlesaca** [comment]
- [ ] header
- [ ] link to: github, JIRA, mailing-list archive
- [ ] commiter list
- [ ] social links

**Comment by dlesaca** [comment]
Need proper social media links (github, twitter, medium, youtube)

**Comment by morganmfritz446** [comment]
https://ibm.ent.box.com/folder/11667466691

**Comment by MadisonJMyers** [comment]
Social Media:

Youtube 
https://www.youtube.com/channel/UCQwUHIc5SjqNIppUH6xbxXQ

Medium 
https://medium.com/@apachesystemmlvideos

Twitter
 https://twitter.com/ApacheSystemML
—> handle: @ApacheSystemML

**Comment by dlesaca** [comment]
@MadisonJMyers Awesome, thanks!
