### ISSUE TITLE
Animated Diagram

### ISSUE THREAD

**Issue by dlesaca** [dlesaca/incubator-systemml-website#16]

**Comment by dlesaca** [comment]
@objectadjective @morganmfritz446 @therenee Can we get a review on this, pleashe?

**Comment by dlesaca** [comment]
@therenee

**Comment by objectadjective** [comment]
This week we can make the animated diagram follow the colors of the current website. Later we'll update for the new visual design.

**Comment by ouroborose** [comment]
Changes to be done:
- Match colors to style guide
- add descriptive text
