### ISSUE TITLE
Upload research to box

### ISSUE THREAD

**Issue by therenee** [dlesaca/incubator-systemml-website#18]

**Comment by therenee** [comment]
uploaded the deck.  Madison is going to upload it in the systemML gmail and @objectadjective will send it out in the email list

**Comment by MadisonJMyers** [comment]
https://drive.google.com/open?id=0B2__Aw0kKn-uTWJ4S0ZvcHhhTE0

**Comment by objectadjective** [comment]
- [ ] Share link in dev list
