### ISSUE TITLE
Illustrations

### ISSUE THREAD

**Issue by dlesaca** [dlesaca/incubator-systemml-website#23]

**Comment by litteredwitherrors** [comment]
### Done When
- [x] Home page hero Illustration is created
- [x] Tutorial page hero illustration is created

**Comment by dlesaca** [comment]
@objectadjective Please add more if the above is lacking

**Comment by ouroborose** [comment]
Tutorial illustration 3-color version (for t-shirts and promotional items) is done; working on full-color version for the webpage
